
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=bible.settings  # Aponta para o módulo correto
      - DB_HOST=${DB_HOST_PROD}
      - DB_NAME=${DB_NAME_PROD}
      - DB_USER=${DB_USER_PROD}
      - DB_PASS=${DB_PASS_PROD}
      - DJANGO_KEY=${DJANGO_KEY_PROD}
    ports:
      - "8000:8000"
    command: >
      sh -c "gunicorn bible.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - /app/static:/app/static
    depends_on:
      - db
  db:
    environment:
      - POSTGRES_DB=${DB_NAME_PROD}
      - POSTGRES_USER=${DB_USER_PROD}
      - POSTGRES_PASSWORD=${DB_PASS_PROD}
    volumes:
      - prod-db-data:/var/lib/postgresql/data

volumes:
  prod-db-data:
